### ISSUE TITLE
🚀 Json5 是不是就可以了？

### ISSUE THREAD

**Issue by cbbfcd** [2betop/json-ast-comments#1]
学芝大佬，[JSON5](https://github.com/json5/json5)，是不是就可以了

**Comment by 2betop** [comment]
关键是，我不知道他能不能反过来，就是把 json 值还原成带注释的字符串。

**Comment by 2betop** [comment]
这个库会在对象里面有个 $$comments 专门存注释，修改后能还原成原始字符串。

**Comment by cbbfcd** [comment]
那应该不行，😂

**Comment by 2betop** [comment]
这个主要用在 amis-editor 里面，修改配置项有多个途径，可以源代码json编辑，或者用配置面板编辑，所以需要 字符串 对象来回转。用过几个插件都有瑕疵，所以自己写了

**Comment by cbbfcd** [comment]
好久不见，学芝大佬还是这么屌，😂
